// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQwrEhvwoiiwPpVPQesOCiHyRca260Qko',
    appId: '1:739768662850:web:e9f77db08d8f591e44e6db',
    messagingSenderId: '739768662850',
    projectId: 'book-tracker-7a077',
    authDomain: 'book-tracker-7a077.firebaseapp.com',
    storageBucket: 'book-tracker-7a077.appspot.com',
    measurementId: 'G-D0L3QFE9LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_-lpaMArhtAj6khZg9bDKxav3HtohaA',
    appId: '1:739768662850:android:ec477f033fa5225044e6db',
    messagingSenderId: '739768662850',
    projectId: 'book-tracker-7a077',
    storageBucket: 'book-tracker-7a077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvV78mfW30qBJVN81doEkhYqzh-0yBUo0',
    appId: '1:739768662850:ios:74fee33fd1d8e80a44e6db',
    messagingSenderId: '739768662850',
    projectId: 'book-tracker-7a077',
    storageBucket: 'book-tracker-7a077.appspot.com',
    iosClientId: '739768662850-hnehpr8obem89j2lpa0pbu06jgiksqle.apps.googleusercontent.com',
    iosBundleId: 'com.book-tracker',
  );
}
